Algoritmo "calculaMedia3Numeros"

Var
// Seção de Declarações das variáveis 
num1: real
num2: real
num3: real
media: real
 
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 escreval("Digite o Primeiro Numero")
 leia(num1)
 escreval("Digite o segundo Numero")
 leia(num2)
 escreval("Digite o Segundo Numero")
 leia(num3)
 
 media<- (num1+num2+num3)/3
 
 escreval("o resultado da media é: ",media)

Fimalgoritmo